### ISSUE TITLE
Update release version

### ISSUE THREAD

**Issue by mostlyjason** [logstash-plugins/logstash-output-loggly#13]
Can we cut a release and update rubygems.org so that people who use the new plugin installer will get the new version in PR #9?

**Comment by mostlyjason** [comment]
@psqmeenakshi I think you can update it in this file? https://github.com/logstash-plugins/logstash-output-loggly/blob/master/logstash-output-loggly.gemspec

**Comment by suyograo** [comment]
@mostlyjason 2.0.3 has been published
