### ISSUE TITLE
Poor performance with http protocol

### ISSUE THREAD

**Issue by Vincent--** [logstash-plugins/logstash-output-loggly#14]
Hi,

We tried to enable the plugin in order to send the logs from our ELK stack to loggly.
This worked straightforward which is very good, but now we have an issue with the performance of the plugin.

Our system generates around 22op/s and the plugin cannot catch up. 
Any idea how to improve the performance of the plugin? I've already try to increase the number of logstash workers without any success...

I believe the issue is related to the protocol.
Thanks in advance for any help.

**Comment by Vincent--** [comment]
See https://github.com/logstash-plugins/logstash-output-loggly/pull/18

**Comment by torrancew** [comment]
Documenting my findings here for other users:

Currently, this plugin sets up and tears down the entire HTTP connection (including a Proxy connection, and HTTPS if enabled), for **each** event it processes. This is obviously a problem (perhaps there was no bulk loggly API at the time this was written, unsure). Using the bulk API is absolutely a must if this plugin is expected to be used in production.

**Comment by Vincent--** [comment]
The PR is available since nearly 20 days now. Could we have an update about it from the maintainer, please?

**Comment by Musashisan** [comment]
+1 We need to use goggly in a production environment, please merge this improvement.

**Comment by anishp55** [comment]
have you looked at using the syslog output plugin for logstash?  with some minor changes to that code push data much quicker than the http plugin

**Comment by Vincent--** [comment]
We use a log server that centralises all the logs from our other servers, so we cannot use syslog in our case. This PR has been made 5 months ago now, I don't understand why there is absolutely no feedback from the maintainers...

**Comment by jordansissel** [comment]
>  I don't understand why there is absolutely no feedback from the maintainers...

Does this plugin have a maintainer? If it does, I don't know who it is. If someone wants to maintain it, I'm open to it.

**Comment by anishp55** [comment]
Vincent it sounds like you guys are pulling from the central server and shipping to loggly with logstash (logstash-output-loggly).  I have a similar setup, but i am now using a modified syslog module to send the data to loggly.  I am going to discuss with my team about releasing my plugin to the public.

**Comment by torrancew** [comment]
@jordansissel I think this raises a larger question about maintainership of modules under this team heading. I'm not sure it's clear to the community whether the core team is taking over maintainership of these plugins or not. If there's a better venue for this discussion, feel free to let me know!

**Comment by jordansissel** [comment]
Our hope was to label plugins as needing maintainers. Sometimes we miss
them. We welcome maintainers for this plugin. I don't think any larger
discussion is needed; we have docs (perhaps insufficient) about plugins,
the community, and the ecosystem we are trying to foster.

**Comment by anishp55** [comment]
Currently I think the version that I've created has a memory leak.  I am
waiting for legal to approve to sharing it in hopes someone can help me fix
said memory leak.  I am able to push a 1.2Tb with not to many problems now.

**Comment by joshuabaird** [comment]
@anishp55 Are you the one that wrote `logstash-output-loggly` which is just a modified version of `logstash-output-syslog` that supports `key`?

**Comment by webmat** [comment]
This has been resolved and released as [v4.0.0](https://rubygems.org/gems/logstash-output-loggly/versions/4.0.0).
