### ISSUE TITLE
Verbose logging to stdout

### ISSUE THREAD

**Issue by rcostanzo** [logstash-plugins/logstash-output-loggly#15]
When NOT running loggly in -v verbose mode, we still get a "Event send to Loggly" message in the stdout log constantly. The adds  up to GB of data on a daily basis and is causing a maintenance problem. It seems like the issue is here: https://github.com/logstash-plugins/logstash-output-loggly/blob/master/lib/logstash/outputs/loggly.rb#L156 where it's doing a `puts` vs. using the `@logger.info` so it's only outputted if loggly is started with the `-v` flag

**Comment by stouf** [comment]
Facing the same issue here... Anything new about it?

**Comment by webmat** [comment]
#26 solved this. Released as v3.0.5.
